name: Install and Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show node version
        run: echo node -v

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
    
      - name: Install dependencies
        run: bun install

      - name: Build the app
        run: bun run build